<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 4.1.2 (Python 3.10.0 on win32)" generated="20211021 09:43:57.641" rpa="false" schemaversion="2">
<suite id="s1" name="Login" source="C:\Users\10135\Desktop\automatizados\robot\testes automatizados\tests\login.robot">
<test id="s1-t1" name="Login na ferramenta">
<kw name="Abrir navegador" library="login" type="SETUP">
<kw name="Open Browser">
<arg>http://www.cervelloesmhomolog.com.br/Quality_NAD</arg>
<arg>firefox</arg>
<msg timestamp="20211021 09:43:57.685" level="FAIL">No keyword with name 'Open Browser' found.</msg>
<status status="FAIL" starttime="20211021 09:43:57.685" endtime="20211021 09:43:57.685"/>
</kw>
<status status="FAIL" starttime="20211021 09:43:57.684" endtime="20211021 09:43:57.686"/>
</kw>
<kw name="Fechar navegador" library="login" type="TEARDOWN">
<kw name="Close Browser">
<msg timestamp="20211021 09:43:57.688" level="FAIL">No keyword with name 'Close Browser' found.</msg>
<status status="FAIL" starttime="20211021 09:43:57.688" endtime="20211021 09:43:57.688"/>
</kw>
<status status="FAIL" starttime="20211021 09:43:57.686" endtime="20211021 09:43:57.688">No keyword with name 'Close Browser' found.</status>
</kw>
<status status="FAIL" starttime="20211021 09:43:57.683" endtime="20211021 09:43:57.688">Setup failed:
No keyword with name 'Open Browser' found.

Also teardown failed:
No keyword with name 'Close Browser' found.</status>
</test>
<status status="FAIL" starttime="20211021 09:43:57.642" endtime="20211021 09:43:57.690"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Login">Login</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20211021 09:43:57.676" level="ERROR">Error in file 'C:\Users\10135\Desktop\automatizados\robot\testes automatizados\tests\login.robot' on line 2: Importing library 'SeleniumLibrary' failed: ModuleNotFoundError: No module named 'SeleniumLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Users\10135\AppData\Local\Programs\Python\Python310\Scripts\robot.exe
  C:\Users\10135\AppData\Local\Programs\Python\Python310\python310.zip
  C:\Users\10135\AppData\Local\Programs\Python\Python310\DLLs
  C:\Users\10135\AppData\Local\Programs\Python\Python310\lib
  C:\Users\10135\AppData\Local\Programs\Python\Python310
  C:\Users\10135\AppData\Local\Programs\Python\Python310\lib\site-packages</msg>
<msg timestamp="20211021 09:43:57.681" level="ERROR">Error in file 'C:\Users\10135\Desktop\automatizados\robot\testes automatizados\resource\login.robot' on line 2: Importing library 'SeleniumLibrary' failed: ModuleNotFoundError: No module named 'SeleniumLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Users\10135\AppData\Local\Programs\Python\Python310\Scripts\robot.exe
  C:\Users\10135\AppData\Local\Programs\Python\Python310\python310.zip
  C:\Users\10135\AppData\Local\Programs\Python\Python310\DLLs
  C:\Users\10135\AppData\Local\Programs\Python\Python310\lib
  C:\Users\10135\AppData\Local\Programs\Python\Python310
  C:\Users\10135\AppData\Local\Programs\Python\Python310\lib\site-packages</msg>
</errors>
</robot>
